language: java
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
matrix:
  allow_failures:
  - jdk: oraclejdk9
notifications:
  email:
    - ansell.peter@gmail.com
after_success:
  - mvn clean test jacoco:report coveralls:report
